IssueTracker/Models/Ticket.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using IssueTracker.Enums;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace IssueTracker.Models
{
    public class Ticket
    {
        public int Id { get; set; }
        
        [Required]
        public string? Subject { get; set; }

        [Required]
        public string? Description { get; set; }

        [Display(Name = "Creation Date")]
        [DataType(DataType.Date)]
        public DateTime CreationDate { get; set; }
        
        public User? Creator { get; set; }

        [Display(Name = "Assigned To")] 
        public User? Assignee { get; set; }
        
        public SeverityEnum? SeverityLevel { get; set; }
        
        public StatusEnum? Status { get; set; }

        [NotMapped]
        public List<SelectListItem> SeverityLevelList { get; } = new List<SelectListItem> {
            new SelectListItem { Text = "Critical", Value = SeverityEnum.Critical.ToString() },
            new SelectListItem { Text = "Important", Value = SeverityEnum.Important.ToString() },
            new SelectListItem { Text = "Normal", Value = SeverityEnum.Normal.ToString()},
            new SelectListItem { Text = "Low", Value = SeverityEnum.Low.ToString() }
        };

        [NotMapped]
        public List<SelectListItem> StatusList { get; } = new List<SelectListItem> {
            new SelectListItem { Text = "New", Value = StatusEnum.New.ToString() },
            new SelectListItem { Text = "Investigation", Value = StatusEnum.Investigation.ToString() },
            new SelectListItem { Text = "Closed", Value = StatusEnum.Closed.ToString()},
            new SelectListItem { Text = "Hold", Value = StatusEnum.Hold.ToString() },
            new SelectListItem { Text = "Awaiting Customer Response", Value = StatusEnum.AwaitingCustomerResponse.ToString() },
            new SelectListItem { Text = "In Development", Value = StatusEnum.InDevelopment.ToString() }
        };
    }
}

IssueTracker/Controllers/TicketsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IssueTracker.Data;
using IssueTracker.Models;
using Microsoft.AspNetCore.Authorization;

namespace IssueTracker.Controllers
{
    [Authorize]
    public class TicketsController : Controller
    {
        private readonly IssueTrackerContext _context;

        public TicketsController(IssueTrackerContext context)
        {
            _context = context;
        }

        // GET: Tickets
        public async Task<IActionResult> Index(string Creator, string Assignee, string searchString)
        {
         var tickets = from ticket in _context.Tickets
                          select ticket;

            if (!string.IsNullOrEmpty(searchString))
            {
                tickets = tickets.Where(ticket => ticket.Subject.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(Creator))
            {
                User selectedCreator = GetSelectedUserByName(Creator);

                tickets = tickets.Where(x => x.Creator == selectedCreator);
            }

            if (!string.IsNullOrEmpty(Assignee))
            {
                User selectedCreator = GetSelectedUserByName(Assignee);

                tickets = tickets.Where(x => x.Assignee == selectedCreator);
            }

            var userSelectList = await MakeUserSelectList();

            var creatorVM = new FilterViewModel
            {
                Creators = userSelectList,
                Assignees = userSelectList,
                Tickets = await tickets.ToListAsync(),
                SearchString = searchString
            };

            return View(creatorVM);
        }

        // GET: Tickets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tickets = await _context.Tickets
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tickets == null)
            {
                return NotFound();
            }
            //Run this method to populate Creator property in ticket data. Data does not need to be retained.
            await MakeUserSelectList();

            return View(tickets);
        }

        // GET: Tickets/Create
        public async Task<IActionResult> Create()
        {
            var usersList = MakeUserSelectList();
            ViewData["UsersList"] = await usersList;

            var ticket = new Ticket { CreationDate = DateTime.Today, SeverityLevel = Enums.SeverityEnum.Normal, Status = Enums.StatusEnum.New };
            return View(ticket);
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Subject,Description,CreationDate,Creator,Assignee,SeverityLevel,Status")] Ticket tickets, string selectedCreator, string assignedUser)
        {
             if (ModelState.IsValid)
            {
                var creator = GetSelectedUserByName(selectedCreator);
                var assignee = GetSelectedUserByName(assignedUser);
                tickets.Creator = creator;
                tickets.Assignee = assignee;
                tickets.Status = Enums.StatusEnum.New;

                _context.Add(tickets);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            //Ticket creation invalid. Return initial create page to fill user dropdown, default date, status.
            return await Create();
        }

        // GET: Tickets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tickets = await _context.Tickets.FindAsync(id);
            if (tickets == null)
            {
                return NotFound();
            }

            var usersList = MakeUserSelectList();
            ViewData["UsersList"] = await usersList;

            return View(tickets);
        }

        // POST: Tickets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Subject,Description,CreationDate,Creator,Assignee,SeverityLevel,Status")] Ticket tickets, string selectedCreator, string assignedUser)
        {
            if (id != tickets.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    SetTicketCreatorAssignee(tickets, selectedCreator, assignedUser);

                    _context.Update(tickets);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TicketsExists(tickets.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                catch (Exception ex)
                {
                    var message = ex.Message;
                }
                return RedirectToAction(nameof(Index));
            }

            //Ticket edit invalid. Return initial edit page to pre-fill fields.
            return await Edit(id);
        }

        private void SetTicketCreatorAssignee(Ticket tickets, string selectedCreator, string assignedUser)
        {
            var creator = GetSelectedUserByName(selectedCreator);
            var assignee = GetSelectedUserByName(assignedUser);
            tickets.Creator = creator;
            tickets.Assignee = assignee;
        }

        // GET: Tickets/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tickets = await _context.Tickets
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tickets == null)
            {
                return NotFound();
            }
            //Run this method to populate Creator property in ticket data. Data does not need to be retained.
            await MakeUserSelectList();

            return View(tickets);
        }

        // POST: Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tickets = await _context.Tickets.FindAsync(id);
            _context.Tickets.Remove(tickets);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TicketsExists(int id)
        {
            return _context.Tickets.Any(e => e.Id == id);
        }

        private async Task<SelectList> MakeUserSelectList()
        {
            IQueryable<User> creatorQuery = from u in _context.Users
                                            orderby u.Name
                                            select u;
            var creatorsList = new SelectList(await creatorQuery.Distinct().ToListAsync());
            return creatorsList;
        }

        private User GetSelectedUserByName(string name)
        {
            return (from u in _context.Users
                    where u.Name == name
                    select u).First();
        }
    }
}

IssueTracker/Views/Tickets/Create.cshtml
@model IssueTracker.Models.Ticket

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Tickets</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Subject" class="control-label"></label>
                <input asp-for="Subject" class="form-control" />
                <span asp-validation-for="Subject" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreationDate" class="control-label"></label>
                <input asp-for="CreationDate" class="form-control" />
                <span asp-validation-for="CreationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Creator" class="control-label"></label>
                <select asp-for="Creator" name="selectedCreator" asp-items="@((Microsoft.AspNetCore.Mvc.Rendering.SelectList) ViewData["UsersList"])"></select>
                <span asp-validation-for="Creator" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Assignee" class="control-label"></label>
                <select asp-for="Assignee" name="assignedUser" asp-items="@((Microsoft.AspNetCore.Mvc.Rendering.SelectList) ViewData["UsersList"])"></select>
                <span asp-validation-for="Assignee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SeverityLevel" class="control-label"></label>
                @*<input asp-for="SeverityLevel" class="form-control" />*@
                <select asp-for="SeverityLevel" asp-items="Model.SeverityLevelList"></select>
                <span asp-validation-for="SeverityLevel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

IssueTracker/Views/Tickets/Delete.cshtml
@model IssueTracker.Models.Ticket

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tickets</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subject)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dt class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dt>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Creator)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Creator.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Assignee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Assignee.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SeverityLevel)
        </dt>
        <dd class = "col-sm-10">
            @{
                switch (Model.SeverityLevel)
                {
                    case IssueTracker.Enums.SeverityEnum.Critical:
                        <p style="color: red; font: bold">CRITICAL</p>
                        break;

                    case IssueTracker.Enums.SeverityEnum.Important:
                        <p style="color:darkorange; font: bold">Important</p>
                        break;

                    case IssueTracker.Enums.SeverityEnum.Low:
                        <p style="color: blue">Low</p>
                        break;

                    default:
                        <p>Normal</p>
                        break;
                }
            }
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @{
                switch (Model.Status)
                {
                    case IssueTracker.Enums.StatusEnum.Closed:
                        <p style="color: green">Closed</p>
                        break;

                    case IssueTracker.Enums.StatusEnum.AwaitingCustomerResponse:
                        <p>Awaiting Customer Response</p>
                        break;

                    case IssueTracker.Enums.StatusEnum.InDevelopment:
                        <p>In Development</p>
                        break;

                    default:
                        @Html.DisplayFor(model => model.Status)
                        break;
                }
            }
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

IssueTracker/Views/Tickets/Details.cshtml
@model IssueTracker.Models.Ticket

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Tickets</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subject)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dt class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dt>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Creator)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Creator.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Assignee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Assignee.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SeverityLevel)
        </dt>
        <dd class = "col-sm-10">
            @{
                switch (Model.SeverityLevel)
                {
                    case IssueTracker.Enums.SeverityEnum.Critical:
                        <p style="color: red; font: bold">CRITICAL</p>
                        break;

                    case IssueTracker.Enums.SeverityEnum.Important:
                        <p style="color:darkorange; font: bold">Important</p>
                        break;

                    case IssueTracker.Enums.SeverityEnum.Low:
                        <p style="color: blue">Low</p>
                        break;

                    default:
                        <p>Normal</p>
                        break;
                }
            }
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @{
                switch (Model.Status)
                {
                    case IssueTracker.Enums.StatusEnum.Closed:
                        <p style="color: green">Closed</p>
                        break;

                    case IssueTracker.Enums.StatusEnum.AwaitingCustomerResponse:
                        <p>Awaiting Customer Response</p>
                        break;

                    case IssueTracker.Enums.StatusEnum.InDevelopment:
                        <p>In Development</p>
                        break;

                    default:
                        @Html.DisplayFor(model => model.Status)
                        break;
                }
            }
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

IssueTracker/Views/Tickets/Edit.cshtml
@model IssueTracker.Models.Ticket

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Tickets</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Subject" class="control-label"></label>
                <input asp-for="Subject" class="form-control" />
                <span asp-validation-for="Subject" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreationDate" class="control-label"></label>
                <input asp-for="CreationDate" class="form-control" />
                <span asp-validation-for="CreationDate" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Creator" class="control-label"></label>
                <select asp-for="Creator" name="selectedCreator" asp-items="@((Microsoft.AspNetCore.Mvc.Rendering.SelectList) ViewData["UsersList"])"></select>
                <span asp-validation-for="Creator" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Assignee" class="control-label"></label>
                <select asp-for="Assignee" name="assignedUser" asp-items="@((Microsoft.AspNetCore.Mvc.Rendering.SelectList) ViewData["UsersList"])"></select>
                <span asp-validation-for="Assignee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SeverityLevel" class="control-label"></label>
                <select asp-for="SeverityLevel" asp-items="Model.SeverityLevelList"></select>
                <span asp-validation-for="SeverityLevel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" asp-items="Model.StatusList"></select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

IssueTracker/Views/Tickets/Index.cshtml
@model IssueTracker.Models.FilterViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<form asp-controller="Tickets" asp-action="Index" method="get" class="d-flex">
    <p>Filter by:</p>
    <p>
        Creator:
        <select asp-for="Creator" asp-items="Model.Creators">
            <option value="">All</option>
        </select>
         | Assignee: 
        <select asp-for="Assignee" asp-items="Model.Assignees">
            <option value="">All</option>
        </select>
         | Search title: <input type="text" name="SearchString" />
         &nbsp;
        <button type="submit" class="btn btn-primary">Filter</button>
    </p>
</form>
<p>
    <a asp-action="Create">Create New</a>
</p>

<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Tickets[0].Subject)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tickets[0].CreationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tickets[0].Creator)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tickets[0].Assignee)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tickets[0].SeverityLevel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tickets[0].Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Tickets) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Subject)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Creator.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Assignee.Name)
            </td>
            <td>
                @{
                    switch (item.SeverityLevel)
                    {
                        case IssueTracker.Enums.SeverityEnum.Critical:
                            <p class="text-danger"><strong>CRITICAL</strong></p>
                            break;

                        case IssueTracker.Enums.SeverityEnum.Important:
                            <p class="text-warning" style="font: bold">Important</p>
                            break;

                        case IssueTracker.Enums.SeverityEnum.Low:
                            <p class="text-info">Low</p>
                            break;

                        default:
                            <p>Normal</p>
                            break;
                    }
                }
            </td>
            <td>
                @{
                    switch (item.Status)
                    {
                        case IssueTracker.Enums.StatusEnum.Closed:
                            <p class="text-success">Closed</p>
                            break;

                        case IssueTracker.Enums.StatusEnum.AwaitingCustomerResponse:
                            <p>Awaiting Customer Response</p>
                            break;

                        case IssueTracker.Enums.StatusEnum.InDevelopment:
                            <p>In Development</p>
                            break;

                        default:
                            @Html.DisplayFor(modelitem => item.Status)
                            break;
                    }
                }
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>